### ISSUE TITLE
Listview Backdrop Quick Filter and Advance Filter changes

### ISSUE THREAD

**Issue by vinayakyengandul** [greytrix/greytrix-ui-kit#76]
**Task : - 18/11/2021**

- [x] Quick Filter Checkbox Checked after change.
- [x] Clear all filter with default value in filter.
- [x] Filter Icon when filter is open than ICON is different flter closing.

**Task : - 22/11/2021**

- [x] Advance Filter new implementation in backdrop Listview

**Task : - 04/12/2021**
- [x] Filter operators changes and saved before applying in API.

**Task : - 06/12/2021**
- [x] Handle Quick filter and Advance filter with flag check and filterFields null check in assets.
- [x] Filter class creating for Operators and Fields.

**Task : - 07/12/2021**
- [x]  After changes all have to move in UI KIT and documentation.
- [x] BackDropListview widget also add in UI Kit.

**Task : - 08/12/2021**

- [x] GtListFilter widget sort filter have to change with multiple fields.
- [x] Filter Operators contains **like** then value will be in %demo%.
- [x] Advance filter default add one filter. 
- [x] Customer- Portal controller not closed issue checked.

**Task : - 09/12/2021**
- [x] GtListFilter widget controller function and variables are moving into UI Kit.
- [x] GtListFilter widget Advnace Filter operators fetch from query and check 

**Task : - 10/12/2021**
- [x] UI KIT documentations for all widgets updated.
- [x] Pdf widget template checking and changes. 

**Task : - 13/12/2021**
- [x] Test Cases for Advance Filter.

**Comment by vinayakyengandul** [comment]
- **Quick Filter Checkbox Checked after change.**

-  **Clear all filter with default value in filter.**
-  **Filter Icon when filter is open than ICON is different flter closing.**

![image](https://user-images.githubusercontent.com/64594463/142799310-bb71d172-ab26-4d41-83cf-a676a48ea827.png)
![image](https://user-images.githubusercontent.com/64594463/142799663-159c3048-3b3b-406c-bbbd-c423e46a5208.png)

**Comment by vinayakyengandul** [comment]
**Task Status [22/11/2021]**

- Advance filter Displayed in UI and saved
![image](https://user-images.githubusercontent.com/64594463/142867373-0b9fe423-84eb-454e-acec-7c8135e16217.png)

**Comment by vinayakyengandul** [comment]
**Task Status :- [06/12/2021]**

- Handle Quick filter and Advance filter with flag check and filterFields null check in assets.

-  Filter class creating for Operators and Fields.

**Comment by vinayakyengandul** [comment]
**Task Status: - 07/12/2021**

-  After changes all have to move in UI KIT and documentation.
-  BackDropListview widget also add in UI Kit.

![image](https://user-images.githubusercontent.com/64594463/145142936-9e32ed15-f412-49d5-b78f-74601e762158.png)
![image](https://user-images.githubusercontent.com/64594463/145142945-84a8ec19-2d19-42f2-937c-c91d76a88f21.png)
![image](https://user-images.githubusercontent.com/64594463/145142971-ef0b599f-2700-420c-8823-b57038fa9fee.png)

**Comment by vinayakyengandul** [comment]
**Task Status [08/12/2021]**

-  GtListFilter widget sort filter have to change with multiple fields.

-  Filter Operators contains like then value will be in %demo%.

-  Advance filter default add one filter.

-  Customer- Portal controller not closed issue checked.

**Comment by vinayakyengandul** [comment]
**Task Status [09/12/2021]**

- GtListFilter widget controller function and variables are moving into UI Kit.
-  GtListFilter widget Advnace Filter operators fetch from query and check.

![image](https://user-images.githubusercontent.com/64594463/145511982-2b1bbe59-864a-49e9-b9fd-5333fbd01964.png)
![image](https://user-images.githubusercontent.com/64594463/145511997-02b6de07-b7bb-4abe-9d03-b4a1677ed448.png)

**Comment by vinayakyengandul** [comment]
**Task Status [10/12/2021]**
-  UI KIT documentations for all widgets updated.
-  Pdf widget template checking and changes.

**Comment by vinayakyengandul** [comment]
**Task Status: - 13/12/2021**

-  Test Cases for Advance Filter.
