### ISSUE TITLE
GtDropdownSearch widget Overflow error

### ISSUE THREAD

**Issue by vinayakyengandul** [greytrix/greytrix-ui-kit#82]
**Task :- [01/12/2021]**

- [x] GtDropdownSearch widget is showing overflow error .

![image](https://user-images.githubusercontent.com/64594463/144165329-d3942d56-cb6d-4146-8181-66483f63dee7.png)

**Task :- [02/12/2021]**

- [x] GtDropdownSearch widget overflow error is solved but dropdown list is not updated.

**Task :- [03/12/2021]**

- [x] GtDropdownSearch widget OverlayEntry Widget is position missing like below
![image](https://user-images.githubusercontent.com/64594463/144543327-d49b47fe-622c-4b28-93a4-2fddd73589dc.png)

**Comment by vinayakyengandul** [comment]
**Task Status [01/12/2021]**

-  GtDropdownSearch widget overflow error was solved.

![image](https://user-images.githubusercontent.com/64594463/144356588-d278643a-0f66-4b4c-a66a-3201b4c65b60.png)

**Comment by vinayakyengandul** [comment]
**Task Status [02/12/2021]**

-  GtDropdownSearch widget dropdown list not updated issue solved.

![image](https://user-images.githubusercontent.com/64594463/144356892-e5e16fd8-ded4-4bb7-a635-6f970bf6d22a.png)

**Comment by vinayakyengandul** [comment]
**Task Status [02/12/2021]**

-  GtDropdownSearch widget OverlayEntry Widget is position missing like below

![image](https://user-images.githubusercontent.com/64594463/144596937-76790c2b-c33c-4338-a824-0c73d11249e7.png)
