### ISSUE TITLE
GtListFilter Widget Advance Filter Improvements 

### ISSUE THREAD

**Issue by vinayakyengandul** [greytrix/greytrix-ui-kit#84]
**Task [14/12/2021]**

- [x] Advance filter make control function convert to statelesswidget.
- [x] Filter is applied then filter icon color will be change.
- [x] Add all test cases in UI Kit test folder.
- [x] After navigate from order to customer List that order customers show only direct filter is applied.

**Task [15/12/2021]**

- [x] GtListFilter widget Advance Filter changes fields type operators is empty then that fields are remove from list.

**Comment by vinayakyengandul** [comment]
**Task Status [14/12/2021]**

-  Advance filter make control function convert to statelesswidget.
-  Filter is applied then filter icon color will be change.
-  Add all test cases in UI Kit test folder.
-  After navigate from order to customer List that order customers show only direct filter is applied.

![image](https://user-images.githubusercontent.com/64594463/145994467-08fb727e-5d89-4a76-85da-1394bd2bee9b.png)
![image](https://user-images.githubusercontent.com/64594463/145994481-52d072d1-0894-4ecf-9913-a53fcede5d16.png)
![image](https://user-images.githubusercontent.com/64594463/145994999-359a6b4d-bb0b-44a3-b6d5-dbee142523d3.png)
![image](https://user-images.githubusercontent.com/64594463/145995010-c82a4f75-b3c0-4ccf-918e-102b1dd70551.png)
