### ISSUE TITLE
GtListWidget Listview new changes

### ISSUE THREAD

**Issue by vinayakyengandul** [greytrix/greytrix-ui-kit#85]
**Task [20/12/2021]**
- [x] active inactive Border is optional default is left.
- [x] List item card circular border removed deafult.
- [x] Pocket HRMS EmployeeDetails Page change with new fields changes with Sandip.

Reference Image :- 
![image](https://user-images.githubusercontent.com/64594463/146746833-65630c5a-94f7-4ecb-b266-7d0611749eff.png)

 **Task [21/12/2021]**

- [x]  Listview Default CardMargin is changed and check in hrms app listing screens.
- [x] Listview IsActive border color also take inputs.
- [x] GtDropDownFormField widget items type is handle both type List<dynamic> and map<String, dyanmic>, and also custom dropdownmenuItem option.

**Comment by vinayakyengandul** [comment]
**Task Status [20/12/2021]**

-  Pocket HRMS EmployeeDetails Page change with new fields changes with Sandip.
- 
-  active inactive Border is optional default is left.

-  List item card circular border removed deafult.

![image](https://user-images.githubusercontent.com/64594463/146869299-1068c94a-61fa-468d-a3f5-e70f2c25eee1.png)

**Comment by vinayakyengandul** [comment]
**Task Status: [21/12/2021]**

-  Listview Default CardMargin is changed and check in hrms app listing screens.

-  Listview IsActive border color also take inputs.

-  GtDropDownFormField widget items type is handle both type List and map<String, dyanmic>, and also custom dropdownmenuItem option.

![image](https://user-images.githubusercontent.com/64594463/146932713-1548542d-8fcd-433d-9272-e9757abde9bb.png)
![image](https://user-images.githubusercontent.com/64594463/146932780-177dfa6f-48be-4bc3-8eb5-0f8e831fa942.png)
