### ISSUE TITLE
Widgets Issues 

### ISSUE THREAD

**Issue by vinayakyengandul** [greytrix/greytrix-ui-kit#91]
**Task [30/12/2021]**

- [x] PDF Body fields is compulsory need empty array as input

- [x]  Confirm the code changes for PDF sections maxRow and Columns values if by mistake send 0 to any of te fields PDF widget doesn't show error but kept showing loading Icon

- [x] GtTagTextField autocomplete Widget - remove input tagList.

**Comment by vinayakyengandul** [comment]
**Task Status [30/12/2021]**

- PDF Body fields is compulsory need empty array as input

-  Confirm the code changes for PDF sections maxRow and Columns values if by mistake send 0 to any of te fields PDF widget doesn't show error but kept showing loading Icon

-  GtTagTextField autocomplete Widget - remove input tagList.
