### ISSUE TITLE
Customer-Portal project  Modules edit pages design changes

### ISSUE THREAD

**Issue by vinayakyengandul** [greytrix/greytrix-ui-kit#92]
**Task [31/12/2021]**

- **Customer-Portal project  Modules edit pages design changes**

- [x] https://user-images.githubusercontent.com/55871576/142621376-c59efb81-5b45-4880-95ff-047180dfe0f4.png
- [x] https://user-images.githubusercontent.com/55871576/142833608-be4bbc6a-d127-45f9-bd23-0cbd462e9d2e.png
- [x] https://user-images.githubusercontent.com/55871576/142621453-1ab99775-2292-4c2c-935b-e148cf80fd6d.png
- [x] https://user-images.githubusercontent.com/55871576/145997021-18804d6e-8a35-4675-beb2-a83f00975046.png
- [x] https://user-images.githubusercontent.com/55871576/145996894-6b9070b5-80bc-4796-9cc9-b26d4d5e785a.png

**Task [3/1/2022]**

- **module form Icons selection widget**

- [x] Update new module form Icons selection widget.

![image](https://user-images.githubusercontent.com/64594463/147897692-cfd98ca7-ffb6-4261-b306-4f3eb7ac90e1.png)

**Task [4/1/2022]**

- [x] Update Standard fields view UI Design improvement.

**Comment by vinayakyengandul** [comment]
**Task Status [31/12/2021]**

- UI changes
![image](https://user-images.githubusercontent.com/64594463/147825061-d125fcac-c9fc-4816-a2c8-8c73be11eadd.png)

**Comment by vinayakyengandul** [comment]
**Task Status : [3/1/2022]**

-  Update new module form Icons selection widget.
![image](https://user-images.githubusercontent.com/64594463/147938483-533873e3-69eb-4a25-b3fd-bac3735de39f.png)
![image](https://user-images.githubusercontent.com/64594463/147938536-fca8c311-a3ca-41e4-b5ed-2d3a1bf19bf2.png)

**Comment by vinayakyengandul** [comment]
**Task Status [4/1/2021]**

- Update Standard fields view UI Design improvement.

![image](https://user-images.githubusercontent.com/64594463/148059585-defcb943-6eeb-48d6-a818-725e27b45147.png)
![image](https://user-images.githubusercontent.com/64594463/148059653-f96025ae-53ad-4e82-a33e-1f41bbb477be.png)
![image](https://user-images.githubusercontent.com/64594463/148059855-4c39d4ef-a17a-40ea-bdd5-95b25f65c309.png)
