### ISSUE TITLE
PDF widget issue and GtDropdownSearch widget change to refer provided buildContext for overlay

### ISSUE THREAD

**Issue by SameerChorge94** [greytrix/greytrix-ui-kit#98]
Task:
- PDF Widget issue faced for the pdf body table content 

Issue:
> Unhandled Exception: Exception: This widget created more than 20 pages. This may be an issue in the widget or the document.

Tasks:
# 11 February 2022
- [x] To check the cause of the issue 
- [x] To check workaround for the issue

# 14 February 2022
- [x] To check workaround for the issue

# 15 February 2022
Solution Reference:
`https://github.com/DavBfr/dart_pdf/issues/114#issuecomment-679944230 `
- [x] To implement workaround for the PDF issue 
- [x] Run the widget test cases to check if widget is not breaking with new updates 

# 16 February 2022
- [x] PDF widget updates for the maxPage input option expose 
- [x] GtDropdownSearch widget updates to follow the provided build context

**Comment by SameerChorge94** [comment]
**Task Status [ 11 February 2022 ]:**

- Issue caused due to the PDF body data content table , tried to put the long string with new lines 
- Checked for workaround to handle same in widget

**Comment by SameerChorge94** [comment]
**Task Status [ 14 February 2022 ]**

 Meetings :
- Call with shyrea on dropdownsearch widget issue
- Call with mayuresh, bhavesh and prathamesh on PDF widget issue 

Coding:
- Continued working on PDF widget issue 
- Discussion with bhavesh for pdf report format and sample reference
- PDF widgets options checked to display the long strings 
- PDF widget solutions tried as per the existing package issues 
- Worked on changes in PDF widget UI kit

**Comment by SameerChorge94** [comment]
**Task Status [ 15 February 2022 ]**

 **Coding :**
- Continuing Working on PDF widget issue workaround implementation in UI Kit 
- Pdf widget changes tested with multile tables data 
- Worked on GtTextFormField widget for exposing the input paramters 
- Worked on the GtDropdownSearch widget for input to set the BuildContext for dropdown result view

**Comment by SameerChorge94** [comment]
**Task Status [ 16 February 2022 ]:**

**Coding :**
- Worked on PDF widget changes
- Worked on PDF widget issue changes and Core plugin changes for the API timeout input option expose
