### ISSUE TITLE
UI Kit widgets updates

### ISSUE THREAD

**Issue by SameerChorge94** [greytrix/greytrix-ui-kit#99]
Tasks:

- [x] GtFilter widget update for exposing TextFilter onEditingComplete option
- [x] GtDropdownSearch widget updates shared by mayuresh to integrate in UI Kit
- [x] To create and merge the PR for same changes with changeLog and readme Updates

**Comment by SameerChorge94** [comment]
**Task Status [  17 February 2022 ]**

 Coding :
- Worked on UIKit changes for filter widgets quick filter 
- Worked on Dropdownsearch widget changes merged by mayuresh 
- Widgets changes tested with sample Example repo examples

**Comment by SameerChorge94** [comment]
**Task Status [ 18 February 2022 ]:**


Coding :
- Worked on UI kit dropdownsearch widget changes provided by mayuresh and shreya 
- Widgets changes tested with the widgets sample app
- UI Kit finalized Changes comitted to the github for PR creation

**Comment by SameerChorge94** [comment]
**Task Status [ 21 Feb 2022 ]:**

Coding:
- UI Kit changes PR created and merged
